#!/bin/zsh

# p10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# fzf
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
# fd-git
git clone https://github.com/junegunn/fzf-git.sh.git
# fd
sudo apt install fd-find
# bat
sudo apt install bat
# eza
sudo apt install -y gpg
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza
#zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
#zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


#nvim kickstart
while true; do
        read  "a?Nvim is installed from my forked CzarnowskiJ/kickstart.vim. Do you want to install it? [y/n]: "
        if [["$a" =~ ^[Yy]$ ]]; then
                echo "Installing nvim from CzarnowskiJ/kickstart.vim"
                sudo add-apt-repository ppa:neovim-ppa/unstable -y
                sudo apt update
                sudo apt install make gcc ripgrep unzip git xclip neovim
                git clone https://github.com/CzarnowskiJ/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
                break
        elif [["$a" =~ ^[Nn]$ ]]; then
                echo "Installation of vim canceld"
                break
        else
                echo "Wrong type. Use 'y' or 'n'"
        fi
done
